version: "3.1"
services:
  discovery:
    build: ../platform-services/discovery/target
    ports:
      - "8761:8761"
    volumes:
      - ~/.m2/repository:/root/.m2/repository
  apigateway:
    build: ../platform-services/api-gateway/target
    ports:
      - "9393:9393"
    volumes:
      - ~/.m2/repository:/root/.m2/repository
    links:
      - discovery