version: "3.1"
services:
  discovery:
    build: ../platform-services/discovery/target
    ports:
      - "8761:8761"
    volumes:
      - ~/.m2/repository:/root/.m2/repository
  apigateway:
    build: ../platform-services/api-gateway/target
    ports:
      - "9393:9393"
    volumes:
      - ~/.m2/repository:/root/.m2/repository
    links:
      - discovery
  tenant1:
    image: postgres:13.3
#    build: ../business-services/common/target
    environment:
      POSTGRES_DB: "tenant1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Way_0804"
    ports:
      - "5432:5432"
    volumes:
      -  ~/PostgreSQL/tenants/db/init/tenant1:/docker-entrypoint-initdb.d
#      - $PWD/../business-services/common/src/main/resources/db/init/tenant1:/docker-entrypoint-initdb.d
  tenant2:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "tenant2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Way_0804"
    ports:
      - "5433:5432"
    volumes:
      -  ~/PostgreSQL/tenants/db/init/tenant2:/docker-entrypoint-initdb.d

volumes:
  tenant1:
  tenant2: